version: "3.8"

name: workers

services:
  workers:
    build:
      context: ../../
      dockerfile: build/Dockerfile
#      shm_size: '4gb'
    tmpfs:
      - /dev/shm:rw,noexec,nosuid,size=4g
    environment:
      - MINIO_ENDPOINT=minio:9000
      - DOTENV_FILE=configs/dev/.env
      - DB_CONNECT_STRING=postgres://hseuser:P%40ssw0rd@datasetsdb:5432/datasetsdb
    ports:
      - "8000:8000"
    networks:
      - auth_hse-net

networks:
  auth_hse-net:
    external: true